### ISSUE TITLE
Translations not loaded

### ISSUE THREAD

**Issue by niknetniko** [theantichris/WordPress-Plugin-Boilerplate#21]
While I was using this boilerplate (thanks!), I found that my localisation files weren't loaded. I double checked everything: the text domain, the folder, file names, etc.

I think this is the issue:
`load_plugin_textdomain( $this->text_domain, false, 'lang' );` (line 38)

When I replaced it with this line, it worked fine:
`load_plugin_textdomain( $this->text_domain, false, basename( dirname( __FILE__ ) ) . '/lang' );`

Am I doing something wrong or is this a bug.

**Comment by theantichris** [comment]
It was a bug. I fixed it by adding the $plugin_path to the call.

7352e64
