### ISSUE TITLE
PHP syntax error

### ISSUE THREAD

**Issue by niknetniko** [theantichris/WordPress-Plugin-Boilerplate#22]
In commit 7352e64, to fix the translations, there is this line:

`load_plugin_textdomain( $this->text_domain, false, $plugin_path + '\lang' );`

This should be:

`load_plugin_textdomain( $this->text_domain, false, $this->plugin_path . '\lang' );`

**Comment by theantichris** [comment]
Derp. That's what I get for editing it in GitHub and not an IDE.

2f187b4ae77181d6fe30227ce5cba2a636276285

**Comment by niknetniko** [comment]
The + should also be a .

**Comment by theantichris** [comment]
Sorry about that. I've been working in C# and JavaScript too much.

8de8685796e40b5300489630ebadafa3bc344c22
